export type CardModel = {
  artist: string;
  attack: number;
  cardId: string;
  cardSet: string;
  collectible: boolean;
  cost: number;
  dbfId: number;
  flavor: string;
  health: number;
  img: string;
  imgGold: string;
  locale: string;
  name: string;
  playerClass: string;
  rarity: string;
  spellSchool: string;
  text: string;
  type: string;
};
